-- Snowflake schema foundation for the wealth-management analytics QA project.
-- Run this script only after a Snowflake account, role, and warehouse strategy
-- are ready. Credentials must stay in a local .env file and out of git.

CREATE WAREHOUSE IF NOT EXISTS analytics_wh
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS WEALTH_ANALYTICS;

USE DATABASE WEALTH_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS REPORTING;
CREATE SCHEMA IF NOT EXISTS QA;

-- RAW.SEC_ADV_FIRMS stores real public SEC/IAPD investment adviser firm data.
-- Future RAW.SYNTHETIC_* tables must remain separate from this public regulatory
-- layer so governance, lineage, and interpretation stay clear.
CREATE TABLE IF NOT EXISTS RAW.SEC_ADV_FIRMS (
    FIRM_CRD_NUMBER VARCHAR,
    FIRM_NAME VARCHAR,
    SEC_NUMBER VARCHAR,
    REGISTRATION_STATUS VARCHAR,
    REGISTRATION_STATE VARCHAR,
    MAIN_OFFICE_CITY VARCHAR,
    MAIN_OFFICE_STATE VARCHAR,
    MAIN_OFFICE_ZIP VARCHAR,
    REGULATORY_AUM NUMBER(18,2),
    EMPLOYEE_COUNT NUMBER,
    BRANCH_COUNT NUMBER,
    SOURCE_TYPE VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ
);

-- RAW.SYNTHETIC_* tables store generated private-style operating records.
-- They must not be represented as real customer, advisor, account, or
-- performance data. They are intentionally separate from RAW.SEC_ADV_FIRMS,
-- which contains real public SEC/IAPD adviser firm data.
CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_BRANCHES (
    BRANCH_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_NAME VARCHAR,
    BRANCH_CITY VARCHAR,
    BRANCH_STATE VARCHAR,
    BRANCH_REGION VARCHAR,
    OPENED_DATE DATE,
    IS_ACTIVE BOOLEAN,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_ADVISORS (
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    ADVISOR_NAME VARCHAR,
    ADVISOR_TENURE_YEARS NUMBER(5,2),
    PRIMARY_CLIENT_SEGMENT VARCHAR,
    IS_ACTIVE BOOLEAN,
    START_DATE DATE,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    CLIENT_SEGMENT VARCHAR,
    ACCOUNT_OPEN_DATE DATE,
    ACCOUNT_STATUS VARCHAR,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_MONTHLY_PERFORMANCE (
    PERFORMANCE_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    MONTH_END_DATE DATE,
    BEGINNING_AUM NUMBER(18,2),
    ENDING_AUM NUMBER(18,2),
    NET_NEW_ASSETS NUMBER(18,2),
    REVENUE NUMBER(18,2),
    FEE_RATE NUMBER(8,6),
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

-- Planned future QA tables:
-- QA.SEEDED_ERROR_LABELS: ground-truth labels for injected anomalies.
-- QA.DETECTED_ANOMALIES: rule and statistical anomaly detection output.
