-- Snowflake schema foundation for the wealth-management analytics QA project.
-- Run this script only after a Snowflake account, role, and warehouse strategy
-- are ready. Credentials must stay in a local .env file and out of git.

CREATE WAREHOUSE IF NOT EXISTS analytics_wh
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS WEALTH_ANALYTICS;

USE DATABASE WEALTH_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS REPORTING;
CREATE SCHEMA IF NOT EXISTS QA;

-- RAW.SEC_ADV_FIRMS stores real public SEC/IAPD investment adviser firm data.
-- Future RAW.SYNTHETIC_* tables must remain separate from this public regulatory
-- layer so governance, lineage, and interpretation stay clear.
CREATE TABLE IF NOT EXISTS RAW.SEC_ADV_FIRMS (
    FIRM_CRD_NUMBER VARCHAR,
    FIRM_NAME VARCHAR,
    SEC_NUMBER VARCHAR,
    REGISTRATION_STATUS VARCHAR,
    REGISTRATION_STATE VARCHAR,
    MAIN_OFFICE_CITY VARCHAR,
    MAIN_OFFICE_STATE VARCHAR,
    MAIN_OFFICE_ZIP VARCHAR,
    REGULATORY_AUM NUMBER(18,2),
    EMPLOYEE_COUNT NUMBER,
    BRANCH_COUNT NUMBER,
    SOURCE_TYPE VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ
);

-- RAW.SYNTHETIC_* tables store generated private-style operating records.
-- They must not be represented as real customer, advisor, account, or
-- performance data. They are intentionally separate from RAW.SEC_ADV_FIRMS,
-- which contains real public SEC/IAPD adviser firm data.
CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_BRANCHES (
    BRANCH_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_NAME VARCHAR,
    BRANCH_CITY VARCHAR,
    BRANCH_STATE VARCHAR,
    BRANCH_REGION VARCHAR,
    OPENED_DATE DATE,
    IS_ACTIVE BOOLEAN,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_ADVISORS (
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    ADVISOR_NAME VARCHAR,
    ADVISOR_TENURE_YEARS NUMBER(5,2),
    PRIMARY_CLIENT_SEGMENT VARCHAR,
    IS_ACTIVE BOOLEAN,
    START_DATE DATE,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    CLIENT_SEGMENT VARCHAR,
    ACCOUNT_OPEN_DATE DATE,
    ACCOUNT_STATUS VARCHAR,
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_MONTHLY_PERFORMANCE (
    PERFORMANCE_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    MONTH_END_DATE DATE,
    BEGINNING_AUM NUMBER(18,2),
    ENDING_AUM NUMBER(18,2),
    NET_NEW_ASSETS NUMBER(18,2),
    REVENUE NUMBER(18,2),
    FEE_RATE NUMBER(8,6),
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

-- Corrupted synthetic performance exists only for QA evaluation. These are not
-- production financial records and should never be treated as clean reporting
-- data.
CREATE TABLE IF NOT EXISTS RAW.SYNTHETIC_MONTHLY_PERFORMANCE_CORRUPTED (
    PERFORMANCE_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    BRANCH_ID VARCHAR,
    MONTH_END_DATE DATE,
    BEGINNING_AUM NUMBER(18,2),
    ENDING_AUM NUMBER(18,2),
    NET_NEW_ASSETS NUMBER(18,2),
    REVENUE NUMBER(18,2),
    FEE_RATE NUMBER(8,6),
    SOURCE_TYPE VARCHAR,
    GENERATED_AT TIMESTAMP_NTZ
);

-- QA.GROUND_TRUTH_INJECTED_ERRORS is the answer key for seeded-error QA. It is
-- used to measure future detection rules with precision, recall, and false
-- positive rates. These rows document intentional corruptions, not production
-- events.
CREATE TABLE IF NOT EXISTS QA.GROUND_TRUTH_INJECTED_ERRORS (
    ERROR_ID VARCHAR,
    PERFORMANCE_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    BRANCH_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    MONTH_END_DATE DATE,
    ERROR_TYPE VARCHAR,
    FIELD_NAME VARCHAR,
    ORIGINAL_VALUE VARCHAR,
    CORRUPTED_VALUE VARCHAR,
    SEVERITY VARCHAR,
    DETECTION_FAMILY VARCHAR,
    EXPLANATION VARCHAR,
    INJECTED_AT TIMESTAMP_NTZ
);

-- QA.DETECTION_RESULTS stores detected QA flags from both hard_rule and
-- statistical_rule detectors. Later phases will score these rows against
-- QA.GROUND_TRUTH_INJECTED_ERRORS.
CREATE TABLE IF NOT EXISTS QA.DETECTION_RESULTS (
    DETECTION_ID VARCHAR,
    RULE_NAME VARCHAR,
    DETECTION_FAMILY VARCHAR,
    PERFORMANCE_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    BRANCH_ID VARCHAR,
    FIRM_CRD_NUMBER VARCHAR,
    MONTH_END_DATE DATE,
    FIELD_NAME VARCHAR,
    OBSERVED_VALUE VARCHAR,
    EXPECTED_CONDITION VARCHAR,
    SEVERITY VARCHAR,
    EXPLANATION VARCHAR,
    DETECTED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS QA.EVALUATION_METRICS (
    EVALUATION_SCOPE VARCHAR,
    DETECTION_FAMILY VARCHAR,
    RULE_NAME VARCHAR,
    THRESHOLD_LABEL VARCHAR,
    TRUE_POSITIVES NUMBER,
    FALSE_POSITIVES NUMBER,
    FALSE_NEGATIVES NUMBER,
    GROUND_TRUTH_COUNT NUMBER,
    DETECTION_COUNT NUMBER,
    PRECISION FLOAT,
    RECALL FLOAT,
    FALSE_POSITIVE_RATE FLOAT,
    F1_SCORE FLOAT,
    EVALUATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS QA.DETECTION_GROUND_TRUTH_MATCHES (
    PERFORMANCE_ID VARCHAR,
    ERROR_TYPE VARCHAR,
    RULE_NAME VARCHAR,
    DETECTION_FAMILY VARCHAR,
    MATCH_STATUS VARCHAR,
    THRESHOLD_LABEL VARCHAR,
    EXPLANATION VARCHAR
);

-- Planned future QA tables:
-- QA.DETECTED_ANOMALIES: rule and statistical anomaly detection output.
